/* @auth Gary Steelman
   @file steelman.sql
   @date 6 Apr 2010
   @class CS238 - Dan Lin
*/

/*DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE DEPT_LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE PROJECT CASCADE CONSTRAINTS;
DROP TABLE WORKS_ON CASCADE CONSTRAINTS;
DROP TABLE DEPENDENT CASCADE CONSTRAINTS;*/

-- TABLE CREATION
CREATE TABLE DEPARTMENT (
DNAME VARCHAR(15) NOT NULL,
DNUMBER INT NOT NULL,
MGRSSN CHAR(9) UNIQUE NOT NULL,
MGRSTARTDATE DATE,
PRIMARY KEY (DNUMBER)
);

CREATE TABLE EMPLOYEE (
FNAME VARCHAR(15) NOT NULL,
MINIT CHAR,
LNAME VARCHAR(15) NOT NULL,
SSN CHAR(9),
BDATE DATE,
ADDRESS VARCHAR(30),
SEX CHAR,
SALARY DECIMAL(10,2),
SUPERSSN CHAR(9),
DNO INT NOT NULL,
PRIMARY KEY (SSN),
FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER) ON DELETE CASCADE
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT CONSTRAINT_SUPERSSN
FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE (SSN) ON DELETE CASCADE
INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_SSN 
FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE (SSN) ON DELETE CASCADE
INITIALLY DEFERRED DEFERRABLE;

CREATE TABLE DEPT_LOCATIONS (
DNUMBER INT NOT NULL,
DLOCATION VARCHAR(20),
PRIMARY KEY(DNUMBER, DLOCATION),
FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER) ON DELETE CASCADE
);

CREATE TABLE PROJECT (
PNAME VARCHAR(20),
PNUMBER INT NOT NULL,
PLOCATION VARCHAR(20),
DNO INT NOT NULL,
PRIMARY KEY (PNUMBER),
FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER) ON DELETE CASCADE
);

CREATE TABLE WORKS_ON (
ESSN CHAR(9) NOT NULL,
PNO INT NOT NULL,
HOURS DECIMAL(4,1),
PRIMARY KEY (ESSN, PNO),
FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE,
FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER) ON DELETE CASCADE
);

CREATE TABLE DEPENDENT (
ESSN CHAR(9) NOT NULL,
DEPENDENT_NAME VARCHAR(20) NOT NULL,
SEX CHAR,
BDATE DATE,
RELATIONSHIP VARCHAR(20),
PRIMARY KEY (ESSN, DEPENDENT_NAME),
FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE
);

-- POPULATING THE TABLES
INSERT INTO DEPARTMENT VALUES( 'Research', 5, '333445555', '22/May/1988' );
INSERT INTO DEPARTMENT VALUES( 'Administration', 4, '987654321', '01/Jan/1995' );
INSERT INTO DEPARTMENT VALUES( 'Headquarters', 1, '888665555', '19/Jun/1981' );

INSERT INTO EMPLOYEE VALUES( 'John', 'B', 'Smith', '123456789', '09/Jan/1965', '731 Fondren, Houston, TX', 'M', 30000, '333445555', 5 );
INSERT INTO EMPLOYEE VALUES( 'Franklin', 'T', 'Wong', '333445555', '08/Dec/1965', '638 Voss, Houston, TX', 'M', 40000, '888665555', 5 );
INSERT INTO EMPLOYEE VALUES( 'Alicia', 'J', 'Zelaya', '999887777', '19/Jan/1965', '3321 Castle, Spring, TX', 'F', 25000, '987654321', 4 );
INSERT INTO EMPLOYEE VALUES( 'Jennifer', 'S', 'Wallace', '987654321', '20/Jun/1965', '291 Berry, Bellaire, TX', 'F', 43000, '888665555', 4 );
INSERT INTO EMPLOYEE VALUES( 'Ramesh', 'K', 'Narayan', '666884444', '15/Sep/1965', '975 Fire Oak, Humble, TX', 'M', 38000, '333445555', 5 );
INSERT INTO EMPLOYEE VALUES( 'Joyce', 'A', 'English', '453453453', '31/Jul/1965', '5631 Rice, Houston, TX', 'F', 25000, '333445555', 5 );
INSERT INTO EMPLOYEE VALUES( 'Ahmad', 'V', 'Jabbar', '987987987', '29/Mar/1965', '980 Dallas, Houston, TX', 'M', 25000, '987654321', 4 );
INSERT INTO EMPLOYEE VALUES( 'James', 'E', 'Borg', '888665555', '10/Nov/1965', '450 Stone, Houston, TX', 'M', 55000, NULL, 1 );

COMMIT;

INSERT INTO DEPT_LOCATIONS VALUES( 1, 'Houston' );
INSERT INTO DEPT_LOCATIONS VALUES( 4, 'Stafford' );
INSERT INTO DEPT_LOCATIONS VALUES( 5, 'Bellaire' );
INSERT INTO DEPT_LOCATIONS VALUES( 5, 'Sugarland' );
INSERT INTO DEPT_LOCATIONS VALUES( 5, 'Houston' );

INSERT INTO PROJECT VALUES( 'ProductX', 1, 'Bellaire', 5 );
INSERT INTO PROJECT VALUES( 'ProductY', 2, 'Sugarland', 5 );
INSERT INTO PROJECT VALUES( 'ProductZ', 3, 'Houston', 5 );

INSERT INTO PROJECT VALUES( 'Computerization', 10, 'Stafford', 5 );
INSERT INTO PROJECT VALUES( 'Reorganization', 20, 'Houston', 5 );
INSERT INTO PROJECT VALUES( 'Newbenefits', 30, 'Stafford', 5 );

INSERT INTO WORKS_ON VALUES( '123456789', 1, 32.5 );
INSERT INTO WORKS_ON VALUES( '123456789', 2, 7.5 );
INSERT INTO WORKS_ON VALUES( '666884444', 3, 40 );
INSERT INTO WORKS_ON VALUES( '453453453', 1, 20 );
INSERT INTO WORKS_ON VALUES( '453453453', 2, 20 );
INSERT INTO WORKS_ON VALUES( '333445555', 2, 10 );
INSERT INTO WORKS_ON VALUES( '333445555', 3, 10 );
INSERT INTO WORKS_ON VALUES( '333445555', 10, 10 );
INSERT INTO WORKS_ON VALUES( '333445555', 20, 10 );
INSERT INTO WORKS_ON VALUES( '999887777', 30, 30 );
INSERT INTO WORKS_ON VALUES( '999887777', 10, 10 );
INSERT INTO WORKS_ON VALUES( '987987987', 10, 35 );
INSERT INTO WORKS_ON VALUES( '987987987', 30, 5 );
INSERT INTO WORKS_ON VALUES( '987654321', 30, 20 );
INSERT INTO WORKS_ON VALUES( '987654321', 20, 15 );
INSERT INTO WORKS_ON VALUES( '888665555', 20, NULL );

INSERT INTO DEPENDENT VALUES( '333445555', 'Alice', 'F', '05/Apr/1986', 'Daughter' );
INSERT INTO DEPENDENT VALUES( '333445555', 'Theodore', 'M', '25/Oct/1986', 'Son' );
INSERT INTO DEPENDENT VALUES( '333445555', 'Joy', 'F', '03/May/1986', 'Spouse' );
INSERT INTO DEPENDENT VALUES( '987654321', 'Abner', 'M', '28/Feb/1986', 'Spouse' );
INSERT INTO DEPENDENT VALUES( '123456789', 'Michael', 'M', '04/Jan/1986', 'Son' );
INSERT INTO DEPENDENT VALUES( '123456789', 'Alice', 'F', '30/Dec/1986', 'Daughter' );
INSERT INTO DEPENDENT VALUES( '123456789', 'Elizabeth', 'F', '05/May/1986', 'Spouse' );

--OUTPUT THE FULL TABLES TO CONFIRM CORRECT ENTRY
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPT_LOCATIONS;
SELECT * FROM PROJECT;
SELECT * FROM WORKS_ON;
SELECT * FROM DEPENDENT;

-- A
SELECT LNAME, FNAME 
FROM EMPLOYEE
WHERE DNO=5 AND SSN IN 
( 
  SELECT ESSN
  FROM WORKS_ON
  WHERE HOURS > 10 AND PNO IN 
  ( 
    SELECT PNUMBER 
    FROM PROJECT
    WHERE PNAME='ProductX'
  )
);

-- B
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE EXISTS 
( 
  SELECT * 
  FROM DEPENDENT
  WHERE FNAME=DEPENDENT_NAME AND ESSN=SSN
);

-- C
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE SUPERSSN IN 
( 
  SELECT SSN
  FROM EMPLOYEE
  WHERE FNAME='Franklin' AND LNAME='Wong'
);

-- D
SELECT PNAME, SUM(HOURS)
FROM PROJECT, WORKS_ON
WHERE PNUMBER=PNO
GROUP BY PNAME
ORDER BY SUM(HOURS) ASC
;

-- E
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE NOT EXISTS (
  SELECT PNUMBER
  FROM PROJECT
  WHERE NOT EXISTS (
    SELECT *
    FROM WORKS_ON
    WHERE PNUMBER=PNO AND ESSN=SSN
  )
);

-- F
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE NOT EXISTS (
  SELECT *
  FROM WORKS_ON
  WHERE ESSN=SSN
);

-- G
SELECT DNAME, AVG(SALARY)
FROM DEPARTMENT, EMPLOYEE
WHERE DNUMBER=DNO
GROUP BY DNAME
ORDER BY AVG(SALARY) ASC
;

-- H
SELECT AVG(SALARY)
FROM EMPLOYEE
WHERE SEX='F'
;

-- I
SELECT LNAME, FNAME, ADDRESS
FROM EMPLOYEE
WHERE EXISTS (
  SELECT *
  FROM WORKS_ON, PROJECT
  WHERE PLOCATION='Houston' AND PNO=PNUMBER AND SSN=ESSN 
)
AND NOT EXISTS (
  SELECT *
  FROM DEPT_LOCATIONS
  WHERE DNO=DNUMBER AND DLOCATION='Houston'
);

-- J
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE EXISTS (
  SELECT *
  FROM DEPARTMENT
  WHERE SSN=MGRSSN
)
AND NOT EXISTS (
  SELECT * 
  FROM DEPENDENT
  WHERE SSN=ESSN
);

-- DROP THE TABLES
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE DEPT_LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE PROJECT CASCADE CONSTRAINTS;
DROP TABLE WORKS_ON CASCADE CONSTRAINTS;
DROP TABLE DEPENDENT CASCADE CONSTRAINTS;