PREFIX  dgp32: <http://data-gov.tw.rpi.edu/vocab/p/32/>
SELECT  ?lat ?lon ?magnitude ?region
WHERE { 
  graph ?g{
  	?s dgp32:magnitude ?magnitude ;
       dgp32:region ?region ;
       dgp32:lat ?lat ;
       dgp32:lon ?lon .
  }
} 
LIMIT 1000