#ifndef BITMAP_H
#define BITMAP_H

#include <pob-eye.h>

// Pre-generated by the example program. This contains the info for outputting text
// to the LCD screen in the form of a bitmap whose pixels contain the text we want
// to display. The different things we can display as text are listed here.
#define IDB_BIGA 0
#define IDB_CROSS 1
#define IDB_KING 2
#define IDB_NOFORMS 3
#define IDB_TOWER 4
#define IDB_TRIANGLE 5
#define IDB_ASCII 0

extern UInt8 bitmap[12326];

#endif

