#ifndef PATTERN_H
#define PATTERN_H

#include <pob-eye.h>

// Pre-generated by the example program. This contains the info the different patterns 
// we want to recognize. The different things we can recognize are listed here.
#define IDP_0_CROSS 1
#define IDP_1_BIGA 2
#define IDP_2_KING 3
#define IDP_3_TOWER 4
#define IDP_4_TREFLE 5
#define IDP_5_TRIANGLE 6
#define IDP_6_CIRCLE 7

extern UInt8 pattern[1135];

#endif
